version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Puerto para React
    environment:
      - CHOKIDAR_USEPOLLING=true  # Hot-reload (en desarrollo)
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Puerto para el backend
    environment:
      - PORT=5000
    volumes:
      - ./server:/app  # Para desarrollo

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contactsdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistir datos

volumes:
  db_data:
