version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Puerto para React
    volumes:
      - .:/app
      - /app/node_modules  # Excluye la carpeta node_modules del host
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # Soluciona problemas de hot-reload en Docker

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Puerto para el backend
    environment:
      - PORT=5000
    volumes:
      - ./server:/app  # Sincroniza la carpeta "server" con el contenedor

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contactsdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistir datos

volumes:
  db_data:
